# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'equalizer.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.stop = QtWidgets.QPushButton(self.frame)
        self.stop.setObjectName("stop")
        self.gridLayout.addWidget(self.stop, 0, 3, 1, 1)
        self.play = QtWidgets.QPushButton(self.frame)
        self.play.setObjectName("play")
        self.gridLayout.addWidget(self.play, 0, 2, 1, 1)
        self.reset = QtWidgets.QPushButton(self.frame)
        self.reset.setObjectName("reset")
        self.gridLayout.addWidget(self.reset, 0, 4, 1, 1)
        self.difference = QtWidgets.QPushButton(self.frame)
        self.difference.setObjectName("difference")
        self.gridLayout.addWidget(self.difference, 0, 5, 1, 1)
        self.save = QtWidgets.QPushButton(self.frame)
        self.save.setObjectName("save")
        self.gridLayout.addWidget(self.save, 0, 6, 1, 1)
        self.load = QtWidgets.QPushButton(self.frame)
        self.load.setObjectName("load")
        self.gridLayout.addWidget(self.load, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 0, 0, 1, 1)
        self.MplWid1 = MplWid1(self.centralwidget)
        self.MplWid1.setObjectName("MplWid1")
        self.gridLayout_3.addWidget(self.MplWid1, 1, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("\n"
"background-color: rgb(149, 149, 149);")
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 5, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 6, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 7, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 8, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 9, 1, 1)
        self.verticalSlider = QtWidgets.QSlider(self.frame_2)
        self.verticalSlider.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.verticalSlider.setMinimum(-15)
        self.verticalSlider.setMaximum(15)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.gridLayout_2.addWidget(self.verticalSlider, 1, 0, 1, 1)
        self.verticalSlider_2 = QtWidgets.QSlider(self.frame_2)
        self.verticalSlider_2.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.verticalSlider_2.setMinimum(-15)
        self.verticalSlider_2.setMaximum(15)
        self.verticalSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_2.setObjectName("verticalSlider_2")
        self.gridLayout_2.addWidget(self.verticalSlider_2, 1, 1, 1, 1)
        self.verticalSlider_3 = QtWidgets.QSlider(self.frame_2)
        self.verticalSlider_3.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.verticalSlider_3.setMinimum(-15)
        self.verticalSlider_3.setMaximum(15)
        self.verticalSlider_3.setSingleStep(1)
        self.verticalSlider_3.setProperty("value", 0)
        self.verticalSlider_3.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_3.setObjectName("verticalSlider_3")
        self.gridLayout_2.addWidget(self.verticalSlider_3, 1, 2, 1, 1)
        self.verticalSlider_4 = QtWidgets.QSlider(self.frame_2)
        self.verticalSlider_4.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.verticalSlider_4.setMinimum(-15)
        self.verticalSlider_4.setMaximum(15)
        self.verticalSlider_4.setSingleStep(1)
        self.verticalSlider_4.setPageStep(10)
        self.verticalSlider_4.setProperty("value", 0)
        self.verticalSlider_4.setSliderPosition(0)
        self.verticalSlider_4.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_4.setInvertedControls(False)
        self.verticalSlider_4.setTickInterval(0)
        self.verticalSlider_4.setObjectName("verticalSlider_4")
        self.gridLayout_2.addWidget(self.verticalSlider_4, 1, 3, 1, 1)
        self.verticalSlider_5 = QtWidgets.QSlider(self.frame_2)
        self.verticalSlider_5.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.verticalSlider_5.setMinimum(-15)
        self.verticalSlider_5.setMaximum(15)
        self.verticalSlider_5.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_5.setObjectName("verticalSlider_5")
        self.gridLayout_2.addWidget(self.verticalSlider_5, 1, 4, 1, 1)
        self.verticalSlider_6 = QtWidgets.QSlider(self.frame_2)
        self.verticalSlider_6.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.verticalSlider_6.setMinimum(-15)
        self.verticalSlider_6.setMaximum(15)
        self.verticalSlider_6.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_6.setObjectName("verticalSlider_6")
        self.gridLayout_2.addWidget(self.verticalSlider_6, 1, 5, 1, 1)
        self.verticalSlider_7 = QtWidgets.QSlider(self.frame_2)
        self.verticalSlider_7.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.verticalSlider_7.setMinimum(-15)
        self.verticalSlider_7.setMaximum(15)
        self.verticalSlider_7.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_7.setObjectName("verticalSlider_7")
        self.gridLayout_2.addWidget(self.verticalSlider_7, 1, 6, 1, 1)
        self.verticalSlider_8 = QtWidgets.QSlider(self.frame_2)
        self.verticalSlider_8.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.verticalSlider_8.setMinimum(-15)
        self.verticalSlider_8.setMaximum(15)
        self.verticalSlider_8.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_8.setObjectName("verticalSlider_8")
        self.gridLayout_2.addWidget(self.verticalSlider_8, 1, 7, 1, 1)
        self.verticalSlider_9 = QtWidgets.QSlider(self.frame_2)
        self.verticalSlider_9.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.verticalSlider_9.setMinimum(-15)
        self.verticalSlider_9.setMaximum(15)
        self.verticalSlider_9.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_9.setObjectName("verticalSlider_9")
        self.gridLayout_2.addWidget(self.verticalSlider_9, 1, 8, 1, 1)
        self.verticalSlider_10 = QtWidgets.QSlider(self.frame_2)
        self.verticalSlider_10.setStyleSheet("background-color: rgb(45, 45, 45);\n"
"")
        self.verticalSlider_10.setMinimum(-15)
        self.verticalSlider_10.setMaximum(15)
        self.verticalSlider_10.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_10.setObjectName("verticalSlider_10")
        self.gridLayout_2.addWidget(self.verticalSlider_10, 1, 9, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 2, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 2, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 2, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frame_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 2, 3, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.frame_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 2, 4, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 2, 5, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 2, 6, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 2, 7, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.frame_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 2, 8, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.frame_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 2, 9, 1, 1)
        self.gridLayout_3.addWidget(self.frame_2, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 650, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.verticalSlider_3.valueChanged['int'].connect(self.label_13.setNum)
        self.verticalSlider_4.valueChanged['int'].connect(self.label_15.setNum)
        self.verticalSlider_5.valueChanged['int'].connect(self.label_16.setNum)
        self.verticalSlider_6.valueChanged['int'].connect(self.label_17.setNum)
        self.verticalSlider_2.valueChanged['int'].connect(self.label_14.setNum)
        self.verticalSlider.valueChanged['int'].connect(self.label_12.setNum)
        self.verticalSlider_7.valueChanged['int'].connect(self.label_18.setNum)
        self.verticalSlider_8.valueChanged['int'].connect(self.label_19.setNum)
        self.verticalSlider_9.valueChanged['int'].connect(self.label_20.setNum)
        self.verticalSlider_10.valueChanged['int'].connect(self.label_21.setNum)
        self.load.clicked.connect(MainWindow.subbands)
        self.play.clicked.connect(MainWindow.play)
        self.stop.clicked.connect(MainWindow.stop)
        self.reset.clicked.connect(MainWindow.reset)
        self.difference.clicked.connect(MainWindow.difference)
        self.save.clicked.connect(MainWindow.save)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.stop.setText(_translate("MainWindow", "stop"))
        self.play.setText(_translate("MainWindow", "play"))
        self.reset.setText(_translate("MainWindow", "reset"))
        self.difference.setText(_translate("MainWindow", "get difference"))
        self.save.setText(_translate("MainWindow", "save"))
        self.load.setText(_translate("MainWindow", "load"))
        self.comboBox.setItemText(0, _translate("MainWindow", "window"))
        self.comboBox.setItemText(1, _translate("MainWindow", "rectangular"))
        self.comboBox.setItemText(2, _translate("MainWindow", "hamming"))
        self.comboBox.setItemText(3, _translate("MainWindow", "hanning"))
        self.label_2.setText(_translate("MainWindow", "0-200HZ"))
        self.label_3.setText(_translate("MainWindow", "201-400HZ"))
        self.label_4.setText(_translate("MainWindow", "401-800HZ"))
        self.label_5.setText(_translate("MainWindow", "801-1500HZ"))
        self.label_6.setText(_translate("MainWindow", "1.5-3KHZ"))
        self.label_7.setText(_translate("MainWindow", " 3-5KHZ"))
        self.label_8.setText(_translate("MainWindow", "5-7KHZ"))
        self.label_9.setText(_translate("MainWindow", "7-10KHZ"))
        self.label_10.setText(_translate("MainWindow", "10-15KHZ"))
        self.label_11.setText(_translate("MainWindow", ">15KHZ"))
        self.label_12.setText(_translate("MainWindow", "  0"))
        self.label_14.setText(_translate("MainWindow", "  0"))
        self.label_13.setText(_translate("MainWindow", "  0"))
        self.label_15.setText(_translate("MainWindow", "  0"))
        self.label_16.setText(_translate("MainWindow", "  0"))
        self.label_17.setText(_translate("MainWindow", "  0"))
        self.label_18.setText(_translate("MainWindow", "  0"))
        self.label_19.setText(_translate("MainWindow", "  0"))
        self.label_20.setText(_translate("MainWindow", "  0"))
        self.label_21.setText(_translate("MainWindow", "  0"))

from mplwid1 import MplWid1

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

